### ISSUE TITLE
Display each post's time

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#12]
**This task can only be done after #4
# ACT 1

Now that ideas are objects we can add other information to the ideas.
- [x] When an idea is saved on the server (index.js), as well as saving the text (idea.text), create a new name-value pair with idea.time = "test";
- [x] Restart you server and test that it's working: in your web browser, post some new ideas, then go to http://localhost:3000/ideas and look at the raw list of ideas. You should see that each idea now has a time as well as a text.
- [x] Instead of always setting the time to "test", get the actual time - try googling "How to get current time javascript"
- [x] There are two places in index.js where you need to set idea.time - once for the example idea that's created at the start, and once for the code when a user creates an idea. Make sure you've done both cases.
- [x] Now In feed.html add the idea.time so it displays after the idea text (note: it will need to be between the `<h2> </h2>` tags). After this change, when you look at http://localhost:3000/feed.html you should see the time for each post - but it's not pretty yet.
# ACT 2

Right now, it looks like this: `2015-09-09T03:42:18.991Z`. Only good if you are a robot  🤖

We can make that nicer, but it will take a lot of code. _Fortunately, someone else has already written the code for us!_ I found a plugin that will work, it's called jquery-dateFormat.
- [x] Include jquery-dateFormat by adding this line to the _head_ section of feed.html

`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-dateFormat/1.0/jquery.dateFormat.js"></script>`

(It should go just below the other `<script>` line in the head section)

Now we have jquery-dateFormat, we can use some new commands. The full documentation is at https://github.com/phstc/jquery-dateFormat, but I pulled out the interesting parts for you here:
- [x] to display the post time nicely, replace `idea.time` with this:

`$.format.prettyDate(idea.time)`
- [x] check that your times are now pretty! They should say something like "11 minutes ago"

This is a good time to commit your changes
# ACT 3

It's kind of confusing that the time is the same color as the text and author name.

Let's give the time its own html tag, with a class so we can give it a different CSS styles.

In feed.html, in the javascript, You will need to add an opening tag before the time, and a closing tag after the time.
- [x] Add `<div class='time'>` before the time value, and `</div>` after the time value.

Because we're writing in javascript, not in real HTML, we need to put the HTML tags inside speech marks so they become a string. (They will turn green in the Atom text editor.) Also, the string needs to be connected to the time with a plus in between.
- [ ] Add a css rule to `style.css` that makes the time display in a different colour.

Check the feed to see that the time is now in a different colour.

**Comment by mgatland** [comment]
this was finished last week
