### ISSUE TITLE
Make submit not go to a new page

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#2]
Currently, when you click 'submit' on the post.html page, you are taken to a new page that says "Thanks for your idea"

This is confusing and not very attractive.

After this change, when you click submit,
1. you stay on the same page
2. a little box pops up that says "Thanks! Your idea was saved!"

All these changes are in post.html

Act 1
- [x] You will need to include jQuery in the page if it is not already included. You do this by adding one line of HTML code to the HEAD of the page. Google "how to add jquery to a page", or look in the head of the feed.html for the line you need to copy.)

jQuery is a library (a whole lot of javascript code that someone else wrote so we don't have to).

Use jQuery to make something happen when you submit the form. To do this:
- [x] in the html, add a class to the `<form>` so we can find it using javascript
- [x] add a pair of `<script>` tags so we can add some javascript between them. Add these near the end of the file, just above `</body>` and `</html>`
- [x] in your script, use jquery to find the form, using its class name. (Do you remember this from the previous activities?). In the star activity we made things happen on click. Here we want to make things happen on "submit", so you'll end up with a line of code like this in your script:

``` javascript
$(".formclassname").on("submit", myCoolFunction);
```
- [x] make a function that will be called when the form is submitted.

``` javascript
var myCoolFunction = function (e) {
    e.preventDefault();
}
```

The line 'e.preventDefault()' disables the browser's built in action (which is to go to a new page).
- [x] TEST: clicking 'submit' should now do nothing! yay :/
## Act 2

history lesson (you can skip this):
Currently, this page works using an old school technique from before JavaScript was a thing. In the HTML is a form. A form is just like a paper form - you fill it in. When you press 'Submit', your browser takes all the things you wrote, puts them together into a message, and POSTs it to the address specified at the top of the form. Then your browser waits for the response from the server. When it arrives, it displays the response ("Thanks for your idea").

In your new function, we now need to make it do a POST that sends the right info to the server.

You could look up "how to POST using jQuery" on google and find some examples, but to save you time I've pulled a good example out here:

``` javascript
      var data = {};
      $.post( "url" , data );
```
- [x] add that code to your function. Change the first argument from "url" to "/ideas" - this is where we are posting to. (It has to match the url the server is listening at in our server code in index.js)
- [x] TEST: clicking submit should now add a new idea to the ideas feed - but it will be null.
### Act 3

How do we get the words the user typed in, and send them to the server?

We will use jQuery to get the part of the HTML page the user is typing into.
Just like the form, we should give this part of the HTML a class so our javascript can select it.
- [x] Add a _class_ to the `<input>` where your idea goes. i.e. `class="ideaInput"`

Now we can select it with jQuery, and get the value out of it using the .val function.

``` javascript
data.idea = $(".ideaInput").val();
```

You'll need to add the line above just after the line `var data = {}`. That means, after we create an empty object named 'data', but before we send the object to the server, we add some information to it.
- [x] Test: you should now be able to correctly submit ideas again.
### Act 4: show feedback
- [x] Add an empty div to the page with a special class like 'note' i.e. `<div class="note"></div>`
- [x] In your function, tell jquery to select that div and change the text inside it to say "Thanks! Your idea was submitted!" using some code like this: `$(".note").text("Thanks! Your idea was submitted");`

Now whenever your function runs, it adds that text into the note.

**Comment by Courtneeey** [comment]
Gondwanaland update
