### ISSUE TITLE
Don't make me delete the example text in the form fields

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/dinolove#24]
As a user, when I want to post a cool Dino Love idea, I have to backspace away the example idea to put in my idea. AND I have to backspace away "put in your name" to put in my name. AND then I have to delete "Add dinosaur picture" to put in my picture URL!

When I start typing in the text box, that example text should just disappear automatically. Ghost text! 👻

Fortunately this feature is built into modern browsers so we don't need to code it ourselves.
- [ ] In post.html, in each of the `input` elements that the user can type text into, instead of setting the `value` (which is meant to be for what the user enters), set the `placeholder` instead.
- [ ] test that the page looks and works correctly.

**Comment by alicedilemma** [comment]
done
