### ISSUE TITLE
change the home page to be the feed page

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#29]
Currently if you visit http://dinolove.herokuapp.com/ you'll be taken to the home page (index.html) but there isn't actually anything useful here!

We should make our feed page the home page!
- [x] Delete index.html and rename feed.html to index.html
- [x] Check that the navbar links still work (they will probably need updating...)

**Comment by ghost** [comment]
Hi could you remove me from recurring these emails
