### ISSUE TITLE
link buttons jump to top of page

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#36]
In post.html when you click on the 'LOVE' button (to generate a phrase) or on any quick pic button, the page scrolls up to the top.

This is because you're clicking on a link that links to "#" which is the top of the page.

We need to prevent the built-in behaviour.

Whenever we call a function using `something.on("click", myFunction)` the myFunction gets passed a special _event_ object. In the funtion that we call, we need to give that object a name by putting it in the function definiton like this

``` javascript
var myFunction = function (e) {
```

(so we added the _e_)

Now inside the function, we can prevent the default action with this command:

``` javascript
e.preventDefault();
```

This tells the browser to disable the built-in behaviour that comes from clicking the link.
-  [x] LOVE button no longer scrolls up
- [x] each dino pic no longer scroll up

**Comment by mgatland** [comment]
the dino icons still do thsi
