### ISSUE TITLE
Change ideas into objects, not strings, so we can save more info about each idea

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#4]
### background

On the server, whenever an idea is saved, we want to save extra info like:
- who posted the idea
- what time it was posted
- maybe a picture was posted too
- maybe the number of Likes or Reblogs the idea has

To support this, we need to change ideas from being a `string` to being an `object`.

A string is a sequence of letters - like a word, a sentence, or a paragraph.

here are some example strings

``` javascript
var string = "hello, i am a string";
var string2 = "i am another string";
var string3 = "a";
var string4 = ""; //this is an empty string!
```

An object, in JavaScript, is a bit like a filing system or a dictionary or a phone book. It can have lots of values and each value is filed under a certain label. Programmers call these "name-value pairs" because each value has a name.

``` javascript
var obby = {}; //create an empty object
obby.rating = 10; //created a name-value pair: the name is rating and the value is the number 10
obby.greeting = "hello, i am a string"; //the name is greeting and the value is a string
```
### Act 1:

You will need to change the data structure a bit, so each idea an object, not just a string.

Look in index.js at the line that pushes the example idea onto the list of ideas.
At the moment, it pushes a string.

`coolIdeas.push("Two cats who solve crimes in Dunedin");`

Replace that line with this:

``` javascript
var idea = {};
idea.text = "Two cats who solve crimes in Dunedin";
coolIdeas.push(idea);
```

Now we are pushing an object.
### Act 2: Displaying the idea again

If you look at the ideas feed, the example idea won't look good any more (remember you'll need to restart the server because you've changed index.js). In _feed.html_, we need to change the code to display the idea.text instead of the whole idea.
- [ ] in feed.html, the idea will now display as [Object object]. You will need to tell the page to display the _text_ value of the object. Basically, wherever it adds `idea` to the page, change it to add `idea.text` instead.
### Act 3: posting ideas

If you try posting an idea and looking at the feed, that's broken now :/ 

That's because the ideas you post are still just a string, not an object.

In index.js currently, we get the value `req.body.idea` which is a string, and save it straight into the coolIdeas list

Instead, we are going to create a new empty object, then put that value in it as the .text field, then save it. Like this:

``` javascript
//delete this: -> coolIdeas.push(req.body.idea); //save a new idea
//add this:
var idea = {};
idea.text = request.body.idea;
coolIdeas.push(idea);
```
- [ ] test that the feed.html now works like it used to, displaying the example idea and the user-posted ideas properly.

Commit your changes. Check everything works!
### Act 4 - saving additional information

Now we can add other information to the ideas.
- [ ] When an idea is saved on the server (index.js), as well as saving the text, create a new name-value pair with idea.time = 0;
- [ ] test that it's working: in your web browser, go to http://localhost:3000/ideas and look at the raw list of ideas. You should see that each idea now has a time as well as a text.
- [ ] Instead of always setting the time to 0, get the actual time - try googling "How to get current time javascript"

**Comment by mieket** [comment]
hi - this should be all done and ready
