### ISSUE TITLE
Publish the app on Heroku

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/dinolove#8]
Heroku is a host that will run our app online so anyone can access it
- [x] get Girl Code's Heroku username and password from matthew or alice
- [x] Do the Heroku node.js deploy tutorial here, **but only go from the start up to the "View Logs" section**: 
  https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction
- [x] Using what you have learned, create a new Heroku app and manually deploy Girl Code to it. It will probably break.

You may have to make some changes to get it working
- 1 [ ] we need to tell Heroku how to start our program. You start it by running `node index.js`, so we need to add that instruction into package.json somehow. Google "package.json start index.js" and you should find an example
- 2 [ ] in index.js, the port it listens on probably needs to change from `3000` to `(process.env.PORT || 3000)` - which means "get the port number from the configuration, or if it hasn't been configured, just used 3000. 
- [x] now try deploying to Heroku again and see if it starts up without errors
- [x] You can link Heroku to Github so it automatically deploys. Do this so Girl Code automatically deploys from now on. (Look up 'automatic github deploy' the Heroku documentation. You do this step by logging into the Heroku website and going to settings or something.)

**Comment by jparulian** [comment]
We have done it!!!!!! We are on the internet!!!!
